# Generated by Django 5.2.2 on 2025-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده ')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'صندوق پیام ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
