# Generated by Django 5.2.2 on 2025-06-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
