# Generated by Django 5.2.2 on 2025-06-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
