# Generated by Django 5.2.2 on 2025-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0011_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of ratings (for display only)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(choices=[(0.0, 'No rating'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=0.0, help_text='Select product rating (0.5 to 5.0)'),
        ),
    ]
