# Generated by Django 5.2.2 on 2025-06-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0012_product_rating_count_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
    ]
